### Get dictionaries
GET {{baseUrl}}/dictionaries
Authorization: {{token}}

### Post dictionary
POST {{baseUrl}}/dictionary
Content-Type: application/json
Authorization: {{token}}

{
  "name": "考研词书1"
}

### Get dictionary words
GET {{baseUrl}}/dictionary/1
Authorization: {{token}}

### Post word to dictionary
POST {{baseUrl}}/dictionary/add
Authorization: {{token}}
Content-Type: application/json

{
 "wordName": "able",
 "dictionaryName": "考研词书1"
}