### Get dictionaries
GET {{baseUrl}}/dictionaries
Authorization: {{token}}

### Post dictionary
POST {{baseUrl}}/dictionary
Content-Type: application/json
Authorization: {{token}}

{
  "name": "考研词书1"
}

### Get dictionary words
GET {{baseUrl}}/dictionary/1
Authorization: {{token}}

### Post link word to dictionary
POST {{baseUrl}}/dictionary/1/word/10
Authorization: {{token}}
Content-Type: application/json
