### Get User
GET {{baseUrl}}/user
Authorization: {{token}}

### Post Sign In (Normal)

POST {{baseUrl}}/user/sign-in
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Post Sign In (Admin)

POST {{baseUrl}}/user/sign-in
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Post Sign Up (Normal)

POST {{baseUrl}}/user/sign-up
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Post Sign Up (Admin)

POST {{baseUrl}}/user/sign-up
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "type": "admin"
}

### Post UpdatePassword

POST {{baseUrl}}/user/password
Content-Type: application/json
Authorization: {{token}}

{
  "password": "test"
}

### GET User Word

GET {{baseUrl}}/user/user-word
Authorization: {{token}}

[
  {
    "userId": 1,
    "wordId": 3,
    "weights": "[[4, 2, 3],[2, 0, 0],[3, 1, 2],[2, 0, 0],[2, 0, 0],[2, 0, 0]]",
    "days": "[1, 3, 2, 6, 18, 54]",
    "nextDate": "2024-05-23T16:00:00.000+00:00",
    "user": {
      "id": 1,
      "username": "admin",
      "password": "admin",
      "type": "admin"
    },
    "word": {
      "id": 3,
      "word": "example1",
      "translation": "示例1的翻译",
      "exampleSentence": "this is an example",
      "frequency": 5,
      "dictionaries": [
        {
          "id": 2,
          "name": "考研词书1"
        },
        {
          "id": 1,
          "name": "考研词书1"
        }
      ]
    }
  },
  {
    "userId": 1,
    "wordId": 10,
    "weights": "[[3, 1, 1],[3, 1, 0],[2, 0, 0],[2, 0, 0],[3, 0, 1]]",
    "days": "[1, 2, 6, 18, 9]",
    "nextDate": "2024-05-25T16:00:00.000+00:00",
    "user": {
      "id": 1,
      "username": "admin",
      "password": "admin",
      "type": "admin"
    },
    "word": {
      "id": 10,
      "word": "art",
      "translation": " 一(个);每一(个);(同类事物中)任一个",
      "exampleSentence": "I need a pencil to write a letter.",
      "frequency": 5,
      "dictionaries": [
        {
          "id": 2,
          "name": "考研词书1"
        }
      ]
    }
  },
  {
    "userId": 1,
    "wordId": 11,
    "weights": "[30]",
    "days": "[30]",
    "nextDate": "2024-05-30T16:00:00.000+00:00",
    "user": {
      "id": 1,
      "username": "admin",
      "password": "admin",
      "type": "admin"
    },
    "word": {
      "id": 11,
      "word": "abandon",
      "translation": "vt.离弃，丢弃;遗弃，抛弃;放弃",
      "exampleSentence": "She had to abandon her car when it broke down.",
      "frequency": 4,
      "dictionaries": [
        {
          "id": 1,
          "name": "考研词书1"
        }
      ]
    }
  }
]

### Post link User Word

POST {{baseUrl}}/user/user-word
Content-Type: application/json
Authorization: {{token}}

{
  "wordId": 14,
  "weights": "[0.5, 0.8, 0.9]",
  "days": "[1, 2, 6, 18, 19]",
  "nextDate": "2024-12-06"
}


### Update link User Word

PUT {{baseUrl}}/user/user-word
Content-Type: application/json
Authorization: {{token}}

{
  "wordId": 10,
  "weights": "[0.7, 0.8, 0.9]",
  "days": "[1, 2, 6, 18, 29]",
  "nextDate": "2024-12-07"
}

### Delete link User Word

DELETE {{baseUrl}}/user/1
Authorization: {{token}}
