### Get User
GET {{baseUrl}}/user
Authorization: {{token}}

### Post Sign In (Normal)

POST {{baseUrl}}/user/sign-in
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Post Sign In (Admin)

POST {{baseUrl}}/user/sign-in
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Post Sign Up (Normal)

POST {{baseUrl}}/user/sign-up
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Post Sign Up (Admin)

POST {{baseUrl}}/user/sign-up
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "type": "admin"
}

### Post UpdatePassword

POST {{baseUrl}}/user/password
Content-Type: application/json
Authorization: {{token}}

{
  "password": "test"
}

### GET User Word

GET {{baseUrl}}/user/user-word
Authorization: {{token}}

### Post User Word

POST {{baseUrl}}/user/user-word
Content-Type: application/json
Authorization: {{token}}

{
  "wordId": 1,
  "weights": "[0.5, 0.8, 0.9]",
  "day": "2024-12-12"
}
