### Get words
GET {{baseUrl}}/words
Authorization: {{token}}

#[
#  {
#    "id": 1,
#    "word": "abandon",
#    "translation": "离弃;放弃;抛弃;遗弃",
#    "exampleSentence": "We had to abandon the car. By the time the rebel troops arrived, the village had already been abandoned.",
#    "frequency": 10,
#    "users": [],
#    "dictionaries": []
#  }
#]

### Get word by name
GET {{baseUrl}}/word?word=abandon
Authorization: {{token}}

#{
#  "id": 1,
#  "word": "abandon",
#  "translation": "离弃;放弃;抛弃;遗弃",
#  "exampleSentence": "We had to abandon the car. By the time the rebel troops arrived, the village had already been abandoned.",
#  "frequency": 10,
#  "users": [],
#  "dictionaries": []
#}

### Get word by id
GET {{baseUrl}}/word/1
Authorization: {{token}}

#{
#  "id": 1,
#  "word": "abandon",
#  "translation": "离弃;放弃;抛弃;遗弃",
#  "exampleSentence": "We had to abandon the car. By the time the rebel troops arrived, the village had already been abandoned.",
#  "frequency": 10,
#  "users": [],
#  "dictionaries": []
#}

### Post word (require admin)
POST {{baseUrl}}/word
Authorization: {{token}}
Content-Type: application/json

{
  "word": "abandon",
  "translation": "离弃;放弃;抛弃;遗弃",
  "exampleSentence": "We had to abandon the car. By the time the rebel troops arrived, the village had already been abandoned.",
  "frequency": 10
}
